"""create_table_user

Revision ID: fda0d426996d
Revises: 
Create Date: 2023-01-12 00:41:04.393089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda0d426996d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('new_password', sa.String(length=128), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('nama', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
